sudo: required
services: 
  - docker

before_install: 
  - docker build -t pintug/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true pintug/docker-react npm run test --coverage
language: generic